baseurl: https://Colvin0315.github.io/
languageCode = "zh-cn"
title = "冷影的 AI 实验室"
theme = "hugo-theme-stack"

# 默认每页显示的文章数
paginate = 10

[params]
    # 核心设置：确保这里和你的文件夹名一致（如果文件夹叫 post 就写 post）
    mainSections = ["post"]
    
    # 侧边栏配置
    [params.sidebar]
        avatar = "img/avatar.png" # 之后把头像放在 static/img/avatar.png
        title = "冷影"
        subtitle = "数学系转 LLM | 数据科学研0"
    
    [[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/Colvin0315"


    # 文章配置
    [params.article]
        math = true          # 开启数学公式支持
        toc = true           # 开启文章目录
        readingTime = true   # 显示阅读时间

    # 底部版权信息
    [params.footer]
        since = 2026
        customText = "写代码也拍日出的数学人"

# 菜单配置
[[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "post"
    name = "文章"
    url = "/post/"
    weight = 2

[[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

# Markdown 渲染配置
[markup]
    [markup.goldmark.renderer]
        unsafe = true # 允许 Markdown 中使用 HTML（对复杂排版很重要）
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = true
        style = "github-dark" # 黑色系代码高亮

